logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080

spring:
  application:
    name: blog 
  datasource:
    url: jdbc:mysql://localhost:3306/webblog
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    property-naming-strategy: SNAKE_CASE
  mail:
    host: smtp.gmail.com
    post: 587
    username: webblogtns@gmail.com
    password: svdovfcnaehhtsfn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signer-key: qj6ZDxyawqxaXeiwYsUjCVy2yVv5/H7u+RMlOcu2yWk19dycEEc/dtJLUq0Zz3zb
  valid-duration: 3600
  refresh-duration: 7200



